schema {
    query: Query
	mutation: Mutation
}

type Query {
    todofile(name: String!): TodoFile
}

type TodoFile {
    name: String!
    path: String
    items: TodoItem!
}

type TodoItem {
    label: String
}

type Mutation{
    createTodoFile(todofile: TodoFileInput): TodoFile
}

input TodoFileInput {
	name: String! 
    path: String
	items: TodoItemInput
}

input TodoItemInput {
    label: String
}